### PR TITLE
Added API contracts

### PR DESCRIPTION
**Pull request by vikhyat187**
Added the API contracts for skill tree
Closes: #4 

PRD: https://docs.google.com/document/d/114ihS42_5M8kN7oM5aQ3XgHN_nxOdr17gG3C3JdeOos/edit?usp=sharing
Entities: https://github.com/Real-Dev-Squad/skill-tree-backend/issues/2

To check the Visual UI we can use https://editor.swagger.io/

### CODE REVIEW

**Review by RitikJaiswal75 — COMMENTED** [review]
image

## 404 and 503 should also be json response why does swagger show only text?

**Comment by RitikJaiswal75** [comment]
NIT: Could you maybe look into integrating a hosting mechanism on every update/PR it so we don't have to look at yaml/copy-paste every time to look into the contracts?

**Comment by vikhyat187** [comment]
> NIT: Could you maybe look into integrating a hosting mechanism on every update/PR it so we don't have to look at yaml/copy-paste every time to look into the contracts?
Need to check for the code editor we have the extensions for free, but hosted ones are paid ones.

**Review by bhtibrewal — DISMISSED** [review]
LGTM for starting out, but needs auth APIs

**Comment by vikhyat187** [comment]
> LGTM for starting out, but needs auth APIs

Yes @kavyarishi19 is creating a doc to decide approach for authentication

**Review by iamitprakash — APPROVED** [review]

**Review by RitikJaiswal75 — APPROVED** [review]

**Pull request merged**
